.Dd $Mdocdate: November 19 2020 $
.Dt DRACO 1
.Os
.Sh NAME
.Nm draco
.Nd a script to convert reddit thread to Org document
.Sh SYNOPSIS
.Nm draco
.Ar <url>
.Sh DESCRIPTION
.Nm
is a script to convert reddit thread to Org document. It accepts a url
& prints the Org document to STDOUT.

It'll also print comments along with their replies. It's limited by
the reddit API.
.Pp
.Sh AUTHOR
.An Andinus Aq Mt andinus@nand.sh
